#!/bin/bash

# inspired by: https://stackoverflow.com/questions/6590688/is-it-bad-to-have-my-virtualenv-directory-inside-my-git-repository

# exit if python3 is not installed
command -v python3 >/dev/null 2>&1 || { echo >&2 "python3 is not installed. Install and retry. Aborting."; exit 1; }

# exit if virtualenv is not installed
command -v virtualenv >/dev/null 2>&1 || { echo >&2 "virtualenv is not installed. See installation guide: https://virtualenv.pypa.io/en/latest/installation/. \nInstall and retry. Aborting."; exit 1; }

# python-requirements.txt was generated by pip freeze
virtualenv --python=python3 --no-site-packages .pyenv && source .pyenv/bin/activate && pip install -r dependencies/python-requirements.txt

echo
read -r -p "Do you wish to add an alias mtact to your bashrc for activating the minitwit python virtualenv? [y/N] " response
if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
then
    echo "# >>>>> minitwit virtualenv setup" >> ~/.bashrc
    echo "alias mtact='source $(pwd)/.pyenv/bin/activate'" >> ~/.bashrc
    echo "# <<<<< minitwit virtualenv setup" >> ~/.bashrc
    echo "Done. Note that you need to source your bashrc for this change to take effect."
else
    echo "To activate virtualenv run: source $(pwd)/.pyenv/bin/activate"
fi

echo "Once activated, to deactivate run: deactivate"
